version = 0.1

[default.deploy.parameters]
stack_name = "rag-chatbot-stack"
resolve_s3 = true
s3_prefix = "rag-chatbot-stack"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "PineconeHost=\"https://ragdbenterprise-4hrlhyw.svc.aped-4627-b74a.pinecone.io\""
image_repositories = []

[default.global.parameters]
region = "us-east-1"
